# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  server:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Port mapping for local testing
    environment:
      MONGO_URL: "mongodb://root:example@mongo:27017/todoapp?authSource=admin"
    depends_on:
      - mongo
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https" # Middleware to redirect to HTTPS
      - "traefik.http.services.todo.loadbalancer.server.port=8000" # Define application port
      - "traefik.http.routers.todo.rule=Host(`todo.haznmo.me`)" # Specify the host
      - "traefik.http.routers.todo.service=todo" # Link to the service
      - "traefik.http.routers.todo.middlewares=redirectscheme" # Enable middleware for redirection
      - "traefik.http.routers.todo_secure.rule=Host(`todo.haznmo.me`)" # Define the host for HTTPS
      - "traefik.http.routers.todo_secure.service=todo" # Link to the service for HTTPS
      - "traefik.http.routers.todo_secure.tls=true" # Enable TLS
      - "traefik.http.routers.todo_secure.tls.certresolver=cloudflare" # Use Cloudflare certificate resolver
    restart: unless-stopped

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: todo_mongo
    ports:
      - "27017:27017" # Expose MongoDB port
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root # MongoDB root username
      MONGODB_INITDB_ROOT_PASSWORD: example # MongoDB root password
    volumes:
      - mongo-data:/data/db # Mount volume for persistent MongoDB data
    networks:
      - proxy # Connect MongoDB to the proxy network

networks:
  proxy:
    name: proxy
    external: true # Use an existing external network

volumes:
  mongo-data: {} # Define a named volume for MongoDB data



# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

