# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"  # Ваше приложение будет доступно по этому порту
    environment:
      MONGO_URL: mongodb://mongo:27017/todoapp
    depends_on:
      - mongo  # Гарантирует, что MongoDB запустится перед приложением

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: todo_mongo  # Название контейнера
    ports:
      - "27017:27017"  # Экспорт порта MongoDB
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root  # Настройка пользователя
      MONGODB_INITDB_ROOT_PASSWORD: example  # Настройка пароля
#      MONGO_INITDB_DATABASE: todoapp  # База данных по умолчанию
    volumes:
      - mongo-data:/data/db  # Персистентное хранилище для MongoDB

volumes:
  mongo-data: {}  # Создаёт постоянный том для MongoDB


# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

