name: CI/CD for ToDoApp

on:
  push:
    branches:
      - main  # Запуск workflow при пуше в ветку main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Устанавливаем Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # 3. Запускаем Traefik
    - name: Deploy Traefik
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/traefik
          docker-compose down
          docker-compose up -d
        debug: true

    # 4. Деплой основного приложения
    - name: Deploy ToDoApp
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/ToDoApp
          docker-compose down
          docker-compose up -d --build

