name: CI/CD for ToDoApp

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Log in to Docker registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }} # add the commit sha instead of latest to avoid overwriting, also add dynamic repo name

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Deploy via SSH to the server
    - name: Deploy ToDoApp
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
            export REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
            cd $REPO_NAME
            git fetch --all --tags
            git checkout ${{ github.sha }}
            docker compose -f compose.yaml pull
            docker compose -f compose.yaml up -d --build
